name: Go

env:
  GIN_MODE: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21' # Ensure compatible Go version
        cache: true

    - name: Revive Action
      uses: morphy2k/revive-action@v2.4.1

    - name: Cache staticcheck
      uses: actions/cache@v3
      with:
        path: ~/.cache/staticcheck
        key: staticcheck-${{ runner.os }}-go-${{ matrix.go-version }}
        restore-keys: |
          staticcheck-${{ runner.os }}-

    - name: Staticcheck
      uses: dominikh/staticcheck-action@v1.3.0 # Updated to latest version if necessary

    - name: Build
      run: |
        go mod download
        go install gotest.tools/gotestsum@latest

    - name: Test
      run: |
        gotestsum --format=standard-verbose --junitfile=junit.xml

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # Always run even if the previous step fails
      with:
        report_paths: '**/junit.xml'
        detailed_summary: true
        include_passed: true
